### ISSUE TITLE
Plugins are not loading

### ISSUE THREAD

**Issue by tobias-piotr** [mlabouardy/pipeline-as-code-with-jenkins#36]
I'm at the end of Chapter 4. Everything gets deployed correctly but when i enter plugins page i see this:

![image](https://user-images.githubusercontent.com/49806746/150157037-97b07094-2f43-4ee1-88c3-d0e7c6d18ee7.png)

In the logs i can find such output:

```
Jan 19, 2022 2:45:38 PM SEVERE jenkins.InitReactorRunner$1 onTaskFailed
Failed Inspecting plugin /var/lib/jenkins/plugins/ace-editor.jpi
java.nio.file.NoSuchFileException: /var/lib/jenkins/plugins/ace-editor/META-INF/MANIFEST.MF
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at org.apache.tools.ant.taskdefs.Expand.extractFile(Expand.java:361)
	at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:199)
Caused: Error while expanding /var/lib/jenkins/plugins/ace-editor.jpi
java.nio.file.NoSuchFileException: /var/lib/jenkins/plugins/ace-editor/META-INF/MANIFEST.MF
	at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:214)
	at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:157)
	at hudson.ClassicPluginStrategy.unzipExceptClasses(ClassicPluginStrategy.java:566)
	at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:490)
Caused: java.io.IOException: Failed to expand /var/lib/jenkins/plugins/ace-editor.jpi
	at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:493)
	at hudson.ClassicPluginStrategy.createPluginWrapper(ClassicPluginStrategy.java:168)
	at hudson.PluginManager$1$3$1.run(PluginManager.java:427)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This is happening for every single plugin.

Any ideas?

**Comment by mlabouardy** [comment]
this should fix the issue @tobias-piotr 
https://github.com/mlabouardy/pipeline-as-code-with-jenkins/commit/fd23093d819f1e82b64eff611da267f5b4b242e2
